//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_LEVANHOANG_PROJECT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTriPj2
    {
        public string Taikhoan { get; set; }
        public string Matkhau { get; set; }
        public Nullable<byte> Trangthai { get; set; }
    }
}
